<<<<<<< HEAD
version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - proxy_landing_page

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./app:/usr/share/caddy:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`${DOMINIO}`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=myresolver"
    networks:
      - proxy_landing_page

networks:
  proxy:
    external: true
